-- CRIANDO USUARIOS DO BANCO DE DADOS E CRIANDO AS ROLES

CREATE USER ‘DAIANA’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘DOUGLAS’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘LILIAN’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘ADRIANA’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘REGIS’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘SHEILA’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘ROBERTA’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘RENANM’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘RENANN’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘ANA’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE USER ‘FERNANDA’ IDENTIFIED BY 'aA1B2C3D4C5!';

CREATE ROLE ‘GERENCIA’ ;

CREATE ROLE ‘ESPECIALISTA’ ;

CREATE ROLE ‘ANALISTA’ ;





GRANT SELECT, INSERT , DELETE , ALTER ON *.* TO ‘GERENCIA’ ;


GRANT SELECT, INSERT , ALTER ON *.* TO ‘ESPECIALISTA’ ;

GRANT SELECT ON *.* TO ‘Analistas’ ;

GRANT ‘GERENCIA’  TO ‘REGIS’ ;

GRANT ‘GERENCIA’ TO ‘FERNANDA’ ;

GRANT ‘GERENCIA’ TO ‘ANA’ ;

GRANT ‘ESPECIALISTA’ TO ‘SHEILA’ ;

GRANT ‘ESPECIALISTA’ TO ‘RENANN’ ;

GRANT ‘ESPECIALISTA’ TO ‘RENANM’ ;

GRANT ‘ESPECIALISTA’ TO ‘ADRIANA’ ;

GRANT ‘ANALISTA’ TO ‘DAIANA’ ;

GRANT ‘ANALISTA’ TO ‘DOUGLAS’ ;

GRANT ‘ANALISTA’ TO ‘LILIAN’ ;

GRANT ‘ANALISTA’ TO ‘ROBERTA’ ;
